sudo: required
services:
  - docker

before_install:
  - docker build -t saikumarch7548/react-test -f ./client/Dockerfile.dev .

script:
  - docker run saikumarch7548/react-test npm test -- --coverage

after_success:
  - docker build -t saikumarch7548/multi-client ./client
  - docker build -t saikumarch7548/multi-nginx ./nginx
  - docker build -t saikumarch7548/multi-server ./server
  - docker build -t saikumarch7548/multi-worker ./worker

# Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
#take those images and push them to docker hub
  - docker push saikumarch7548/multi-client
  - docker push saikumarch7548/multi-nginx
  - docker push saikumarch7548/multi-server
  - docker push saikumarch7548/multi-worker


deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: arn:aws:s3:::elasticbeanstalk-us-east-2-488092440969
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEKY
  secret_access_key:
    secure: $AWS_SECRET_KEY
